import { SPOTS } from "../ui/geometry";
import type { Setup } from "../domain/types";
import { parseSetups } from "./schema";

const colours = [
  { id: "yellow", kind: "colour" as const, colour: "yellow" as const, ...SPOTS.yellow },
  { id: "green", kind: "colour" as const, colour: "green" as const, ...SPOTS.green },
  { id: "brown", kind: "colour" as const, colour: "brown" as const, ...SPOTS.brown },
  { id: "blue", kind: "colour" as const, colour: "blue" as const, ...SPOTS.blue },
  { id: "pink", kind: "colour" as const, colour: "pink" as const, ...SPOTS.pink },
  { id: "black", kind: "colour" as const, colour: "black" as const, ...SPOTS.black },
];

const raw = [
  {
    id: "open-three",
    ladderIndex: 0,
    lesson: "colour-choice",
    title: "Three open reds",
    balls: [
      ...colours,
      { id: "r1", kind: "red", x: 2600, y: 700 },
      { id: "r2", kind: "red", x: 2750, y: 1150 },
      { id: "r3", kind: "red", x: 3050, y: 900 },
      { id: "cue", kind: "cue", x: 1900, y: 900 },
    ],
    coachedLine: [
      { ball: "r1", strength: "medium", spin: "top", why: "Start with the red that leaves you a simple angle on the black. Roll through so you land on it." },
      { ball: "black", strength: "soft", acceptableStrength: ["medium"], spin: "centre", why: "Highest value, and it sits still — take it while the reds are open. Soft stun keeps you close." },
      { ball: "r2", strength: "medium", spin: "centre" },
      { ball: "black", strength: "soft", spin: "centre", why: "The black re-spots, so you can go back to it every time." },
      { ball: "r3", strength: "soft", acceptableStrength: ["medium"], spin: "centre" },
      { ball: "black", strength: "soft", spin: "centre" },
    ],
  },
  {
    id: "awkward-first",
    ladderIndex: 1,
    lesson: "awkward-ball-first",
    title: "One red on the cushion",
    balls: [
      ...colours,
      { id: "r1", kind: "red", x: 3300, y: 120 },
      { id: "r2", kind: "red", x: 2700, y: 950 },
      { id: "r3", kind: "red", x: 2500, y: 1200 },
      { id: "cue", kind: "cue", x: 2000, y: 800 },
    ],
    coachedLine: [
      { ball: "r1", strength: "medium", acceptableStrength: ["firm"], spin: "low", why: "Take the awkward one first, while you still have an angle on it. Screw back off the cushion into the open. Leave it to the end and it becomes the shot that stops your break." },
      { ball: "blue", acceptable: ["pink"], strength: "soft", spin: "centre", why: "Blue sits in the middle and opens up the rest of the table. Pink is fine too." },
      { ball: "r2", strength: "medium", spin: "centre" },
      { ball: "black", strength: "soft", acceptableStrength: ["medium"], spin: "centre" },
      { ball: "r3", strength: "medium", spin: "top" },
      { ball: "black", strength: "soft", spin: "centre" },
    ],
  },
  {
    id: "hold-the-pack",
    ladderIndex: 2,
    lesson: "cluster",
    title: "Two loose, two in a cluster",
    balls: [
      ...colours,
      { id: "r1", kind: "red", x: 2450, y: 500 },
      { id: "r2", kind: "red", x: 2900, y: 1250 },
      { id: "r3", kind: "red", x: 3080, y: 880 },
      { id: "r4", kind: "red", x: 3140, y: 940 },
      { id: "cue", kind: "cue", x: 1800, y: 1080 },
    ],
    coachedLine: [
      { ball: "r1", strength: "medium", spin: "centre", why: "Pot the loose reds first. The cluster is not going anywhere." },
      { ball: "blue", strength: "soft", spin: "centre", why: "Blue keeps you in the middle of the table with a view of everything." },
      { ball: "r2", strength: "medium", spin: "low", why: "Screw back so the pink is on." },
      { ball: "pink", acceptable: ["black"], strength: "medium", spin: "centre", why: "Pink puts you on the right side to split the two reds that are close together." },
      { ball: "r3", strength: "medium", spin: "centre", why: "Now you are on the cluster with a colour to follow." },
      { ball: "black", strength: "soft", spin: "centre" },
      { ball: "r4", strength: "medium", acceptableStrength: ["soft"], spin: "centre" },
      { ball: "black", strength: "soft", spin: "centre" },
    ],
  },
  {
    id: "stay-on-the-blue",
    ladderIndex: 3,
    lesson: "positional-play",
    title: "Three reds around the middle",
    balls: [
      ...colours,
      { id: "r1", kind: "red", x: 2150, y: 550 },
      { id: "r2", kind: "red", x: 2350, y: 1250 },
      { id: "r3", kind: "red", x: 2050, y: 900 },
      { id: "cue", kind: "cue", x: 1300, y: 700 },
    ],
    coachedLine: [
      { ball: "r1", strength: "medium", spin: "low", why: "Screw back towards the middle — from the centre of the table every red is on." },
      { ball: "blue", strength: "soft", spin: "centre", why: "The blue is your home base here. Pot it and you're still in the middle, with the whole table open." },
      { ball: "r2", strength: "medium", spin: "centre" },
      { ball: "blue", strength: "soft", spin: "centre", why: "Back to the blue — it re-spots, so the middle keeps being home." },
      { ball: "r3", strength: "soft", spin: "top" },
      { ball: "blue", strength: "soft", spin: "centre" },
    ],
  },
  {
    id: "off-the-top-cushion",
    ladderIndex: 4,
    lesson: "cushion-work",
    title: "A red under the top cushion",
    balls: [
      ...colours,
      { id: "r1", kind: "red", x: 2450, y: 250 },
      { id: "r2", kind: "red", x: 2950, y: 650 },
      { id: "r3", kind: "red", x: 2800, y: 1250 },
      { id: "cue", kind: "cue", x: 2000, y: 1000 },
    ],
    coachedLine: [
      { ball: "r1", strength: "firm", spin: "top", why: "Play it firm with top. The white runs on, kisses the top cushion and comes back out into the open — let the cushion do the work for you." },
      { ball: "black", strength: "soft", spin: "centre", why: "The cushion has brought you back onto the black's side." },
      { ball: "r2", strength: "medium", spin: "centre" },
      { ball: "pink", acceptable: ["black"], strength: "soft", spin: "centre" },
      { ball: "r3", strength: "medium", spin: "top" },
      { ball: "black", strength: "soft", spin: "centre" },
    ],
  },
  {
    id: "the-nearest-colour",
    ladderIndex: 5,
    lesson: "colour-choice",
    title: "Reds at both ends",
    balls: [
      ...colours,
      { id: "r1", kind: "red", x: 1500, y: 500 },
      { id: "r2", kind: "red", x: 2500, y: 1300 },
      { id: "r3", kind: "red", x: 3000, y: 600 },
      { id: "cue", kind: "cue", x: 900, y: 1000 },
    ],
    coachedLine: [
      { ball: "r1", strength: "medium", spin: "top", why: "Start at the baulk end where the white already is." },
      { ball: "brown", acceptable: ["green"], strength: "soft", spin: "centre", why: "Take the colour you're on. Chasing the black from here loses the white — the brown keeps the break alive." },
      { ball: "r2", strength: "medium", spin: "centre" },
      { ball: "pink", acceptable: ["blue"], strength: "soft", spin: "centre", why: "Nearest colour again — the pink is right there." },
      { ball: "r3", strength: "medium", spin: "centre" },
      { ball: "black", strength: "soft", spin: "centre", why: "Now the black — because now you're on it." },
    ],
  },
  {
    id: "two-ways-in",
    ladderIndex: 6,
    lesson: "positional-play",
    title: "The same red, two angles",
    balls: [
      ...colours,
      { id: "r1", kind: "red", x: 2900, y: 400 },
      { id: "r2", kind: "red", x: 3050, y: 1300 },
      { id: "r3", kind: "red", x: 2450, y: 850 },
      { id: "cue", kind: "cue", x: 2300, y: 400 },
    ],
    coachedLine: [
      { ball: "r1", strength: "soft", spin: "low", why: "Come into this red on its left side — soft screw holds the white above the black, not below it." },
      { ball: "black", strength: "soft", spin: "centre" },
      { ball: "r2", strength: "medium", spin: "top", why: "Roll through on the correct side so the pink is next, not a long blue." },
      { ball: "pink", acceptable: ["black"], strength: "soft", spin: "centre" },
      { ball: "r3", strength: "medium", spin: "centre" },
      { ball: "black", strength: "soft", spin: "centre" },
    ],
  },
  {
    id: "the-long-red",
    ladderIndex: 7,
    lesson: "awkward-ball-first",
    title: "A long red down the bottom",
    balls: [
      ...colours,
      { id: "r1", kind: "red", x: 1200, y: 1650 },
      { id: "r2", kind: "red", x: 2750, y: 700 },
      { id: "r3", kind: "red", x: 2950, y: 1100 },
      { id: "cue", kind: "cue", x: 2450, y: 950 },
    ],
    coachedLine: [
      { ball: "r1", strength: "firm", spin: "low", why: "The long red first. It's the ball that kills breaks — take it while the angle is still there, and screw back up the table." },
      { ball: "blue", acceptable: ["brown"], strength: "medium", spin: "centre", why: "The blue brings you back to the middle after the long journey." },
      { ball: "r2", strength: "medium", spin: "centre" },
      { ball: "black", acceptable: ["pink"], strength: "soft", spin: "centre" },
      { ball: "r3", strength: "medium", spin: "centre" },
      { ball: "black", strength: "soft", spin: "centre" },
    ],
  },
  {
    id: "cannon-into-the-pair",
    ladderIndex: 8,
    lesson: "cushion-work",
    title: "Two loose reds, a pair together",
    balls: [
      ...colours,
      { id: "r1", kind: "red", x: 2300, y: 600 },
      { id: "r2", kind: "red", x: 2500, y: 1150 },
      { id: "r3", kind: "red", x: 3150, y: 1150 },
      { id: "r4", kind: "red", x: 3230, y: 1210 },
      { id: "cue", kind: "cue", x: 1950, y: 700 },
    ],
    coachedLine: [
      { ball: "r1", strength: "medium", spin: "top" },
      { ball: "black", strength: "soft", spin: "centre", why: "Stay up at the black's end — the pair of reds can wait." },
      { ball: "r2", strength: "firm", spin: "top", why: "Firm with top. After the pot the white runs off the bottom cushion and cannons into the pair, knocking them apart." },
      { ball: "pink", acceptable: ["black"], strength: "soft", spin: "centre" },
      { ball: "r3", strength: "medium", spin: "centre", why: "The cannon has left them open — pick off the first." },
      { ball: "black", strength: "soft", spin: "centre" },
      { ball: "r4", strength: "medium", spin: "centre" },
      { ball: "black", strength: "soft", spin: "centre" },
    ],
  },
  {
    id: "open-the-pack",
    ladderIndex: 9,
    lesson: "cluster",
    title: "One loose red, three together",
    balls: [
      ...colours,
      { id: "r1", kind: "red", x: 2400, y: 450 },
      { id: "r2", kind: "red", x: 3150, y: 500 },
      { id: "r3", kind: "red", x: 3250, y: 560 },
      { id: "r4", kind: "red", x: 3180, y: 640 },
      { id: "cue", kind: "cue", x: 1600, y: 1100 },
    ],
    coachedLine: [
      { ball: "r1", strength: "medium", spin: "top", why: "One loose red — use it to get up the table, but don't touch the pack yet." },
      { ball: "blue", strength: "soft", spin: "centre", why: "Hold the middle until you're ready to open them on your terms." },
      { ball: "r2", strength: "medium", spin: "centre", why: "Take the edge red of the pack first — it's the one with a clear pocket." },
      { ball: "black", acceptable: ["pink"], strength: "soft", spin: "centre" },
      { ball: "r3", strength: "medium", spin: "centre" },
      { ball: "black", strength: "soft", spin: "centre" },
      { ball: "r4", strength: "soft", spin: "centre" },
      { ball: "black", strength: "soft", spin: "centre" },
    ],
  },
];

export const SETUPS: Setup[] = parseSetups(raw).sort(
  (a, b) => a.ladderIndex - b.ladderIndex,
);
